version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb+srv://admin:admin@ms-iam.pxztx.mongodb.net/?retryWrites=true&w=majority&appName=ms-iam

volumes:
  mongo_data:
